### ISSUE TITLE
Turn into TYPO3 extension

### ISSUE THREAD

**Issue by mbrodala** [NamelessCoder/typo3-cms-fluid-precompiler#2]
Since this package is targeted at TYPO3 it would make sense to have it as extension. This would also allow for using the Symfony command API available since TYPO3 v8 and thus solve #1.

What do you think?

**Comment by NamelessCoder** [comment]
The TYPO3 extension (BE module) counterpart for this CLI can be found at https://github.com/NamelessCoder/typo3-cms-fluid-precompiler-module. That one is "fully fledged" but this little lib isn't intended to be an extension you have to install; doing it that way would almost require more metadata than the package contains code currently - and would require that the "extension" gets not just installed but also *activated*. One of the goals is to make it possible to generate a prewarmed cache *before* you actually deploy any files (think read-only systems) and demanding a TYPO3 installed somewhat defeats that purpose.

But you are more than welcome to contribute a CLI command for the other package I linked to. That one remains relevant even if this library here becomes redundant - and it is a genuine TYPO3 extension that also makes sense to deploy (as admin-only tool). So a CLI for that would also be welcome (which like this little package does, abstracts the cache warming to be a decision about which extension key - or all - to warm up).

Side note: Fluid itself actually has this as a CLI command, the only reason it doesn't work with TYPO3v8 is render method argument support. In TYPO3v9 I've refactored this so classes will work without the reflection framework, and the Fluid CLI command can warm templates if you pass 1) `TYPO3_PATH_ROOT` and 2) a correct bootstrap class name which is aware of this ENV and uses it when resolving TYPO3 assets. Sadly it won't get to work on TYPO3v8 because it contains ViewHelpers with render method arguments, which will not be accepted for refactoring I'm sure.

**Comment by mbrodala** [comment]
Yes, it would make sense adding a command to that extension instead but that in turn would require to have this extension (and its module) always available on production servers.

So I guess it would make sense to simply add a 3rd package which is an extension and provides the Symfony command?

**Comment by NamelessCoder** [comment]
> So I guess it would make sense to simply add a 3rd package which is an extension and provides the Symfony command?

You know, I think everyone would be happier if this were a built-in command in TYPO3. The code it requires is extremely minimal (since wrapping it in a command handles all arguments and such).

If you didn't notice about the module extension: it has extension configuration to disable the cache menu item and be module alike (and if it were to have a CLI command, I'd also require a toggle for that like the other ones).

**Comment by mbrodala** [comment]
Having this available as native command in TYPO3 would indeed make sense. I'll see if I find time to do this. :-)

**Comment by NamelessCoder** [comment]
Don't forget to add me as reviewer ;)

I'll close this issue - if you end up deciding against a native command in TYPO3 you're more than welcome to create it as PR for the BE module extension. I would be happy with either way but happiest if the core itself had this warmup command (and others like it, in fact, a complete suite to warm up cold caches!).

**Comment by jdoubleu** [comment]
I created a PR for the https://github.com/NamelessCoder/typo3-cms-fluid-precompiler-module typo3 extension to add a console command: https://github.com/NamelessCoder/typo3-cms-fluid-precompiler-module/pull/6
