### ISSUE TITLE
Usage in non-composer TYPO3 installations

### ISSUE THREAD

**Issue by taalas** [NamelessCoder/typo3-cms-fluid-precompiler#6]
Hi,

is there a simple (and/or recommended) way to use this in a non-composer TYPO3 8 installation? Or should one rather be using the extension at:

https://github.com/NamelessCoder/typo3-cms-fluid-precompiler-module

I would prefer having a CLI command to warm up caches.

**Comment by NamelessCoder** [comment]
Hi @taalas,

You should use the extension you link to, rather than this library. You *can* use it without composer although I would not recommend doing so. One way to do that is to download a zip of the extension repository and manually unzip it to TYPO3's extension folder or upload via Extension Manager - but this only works for TYPO3 in non-composer mode.

The extension you link to contains a CLI (via TYPO3's CLI) which also works in non-composer mode but does require a fully installed TYPO3 as context.
